services:
  language-service:
    build: .
    container_name: language-service
    networks: [ss-dev]
    environment:
      SPRING_PROFILES_ACTIVE: docker

      JAVA_TOOL_OPTIONS: "-javaagent:/newrelic/newrelic.jar"
      NEW_RELIC_LICENSE_KEY: "${NEW_RELIC_LICENSE_KEY}"
      NEW_RELIC_APP_NAME: "${NEW_RELIC_APP_NAME}"

    volumes:
      - ./newrelic:/newrelic

networks:
  ss-dev:
    external: true
